### ISSUE TITLE
White space at the bottom of screen

### ISSUE THREAD

**Issue by Ali-Haider8** [laobie/StatusBarUtil#180]
I've got a problem when I use this library, showing a white space below or above the screen

![j9aoq](https://user-images.githubusercontent.com/26713386/37553328-244053a8-29d7-11e8-9879-dffeb1475bb6.jpg)

**Comment by laobie** [comment]
Could you show your layout code？And tell me which method you calling？

**Comment by Ali-Haider8** [comment]
>Could you show your layout code

![screenshot_3](https://user-images.githubusercontent.com/26713386/37681706-804b9a36-2c98-11e8-85da-b6fb6ef2a8c0.png)


>And tell me which method you calling？

`StatusBarUtil.setTransparent(this);`

**Comment by Ali-Haider8** [comment]
It has been Fixed at version 1.5.1
Thanks.

**Comment by laobie** [comment]
OK

**Comment by elsennov** [comment]
Still occur in HTC Android 8.0, using the same method call `setTransparent(activity)`
